function SVMOD:GUI_Damage(panel, data)
	panel:Clear()

	SVMOD:CreateTitle(panel, language.GetPhrase("svmod.damage.vehicle_damage"))

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.physics_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("PhysicsMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.PhysicsMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.physics_damage"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("BulletMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.BulletMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.chance_carbonise"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("CarbonisedChance")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.CarbonisedChance * 100)
	slide:SetMaxValue(100)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.percent_life"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("SmokePercent")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.SmokePercent * 100)
	slide:SetMaxValue(100)
	slide:SetUnit("%")

	local title = SVMOD:CreateTitle(panel, language.GetPhrase("svmod.damage.wheels"))
	title:DockMargin(0, 30, 0, 0)

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.wheel_shot_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("WheelShotMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.WheelShotMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.wheel_collision_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("WheelCollisionMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.WheelCollisionMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.wheel_time_punctured"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("TimeBeforeWheelIsPunctured")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val)
		net.SendToServer()
	end)
	slide:SetValue(data.TimeBeforeWheelIsPunctured)
	slide:SetMaxValue(300)
	slide:SetUnit(language.GetPhrase("svmod.seconds"))

	local title = SVMOD:CreateTitle(panel, language.GetPhrase("svmod.damage.player_damage"))
	title:DockMargin(0, 30, 0, 0)

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.driver_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("DriverMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.DriverMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.passenger_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("PassengerMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.PassengerMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")

	local slide = SVMOD:CreateNumSlidePanel(panel, language.GetPhrase("svmod.damage.exit_multiplier"), function(val)
		net.Start("SV_Settings")
		net.WriteString("Damage")
		net.WriteString("PlayerExitMultiplier")
		net.WriteUInt(1, 2) -- float
		net.WriteFloat(val / 100)
		net.SendToServer()
	end)
	slide:SetValue(data.PlayerExitMultiplier * 100)
	slide:SetMaxValue(200)
	slide:SetUnit("%")
end